# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailnum', models.CharField(max_length=12, unique=True, verbose_name='Tail Number')),
                ('make', models.CharField(max_length=40, verbose_name='Aircraft Make')),
                ('model', models.CharField(max_length=40, verbose_name='Aircraft Model')),
                ('rate_wet', models.IntegerField(blank=True, verbose_name='Wet Rate')),
                ('rate_dry', models.IntegerField(blank=True, verbose_name='Dry Rate')),
                ('speed', models.IntegerField(blank=True, verbose_name='Speed in Knots')),
                ('useful_load', models.IntegerField(blank=True, verbose_name='Useful Load')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Aircraft Image')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Aircraft Image')),
                ('description', models.TextField(verbose_name='Image Description')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.Aircraft')),
            ],
        ),
    ]
