# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name_plural': 'Aircraft'},
        ),
        migrations.AddField(
            model_name='aircraft',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Aircraft Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Primary Image'),
        ),
        migrations.AlterField(
            model_name='aircraftgalleryimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Gallery Image'),
        ),
    ]
