# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:37
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_auto_20171017_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['aircraft_order'], 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.AlterModelOptions(
            name='aircraftequipment',
            options={'ordering': ['equipment_order']},
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='aircraftequipment',
            name='equipment_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='aircraftequipment',
            name='aircraft',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.Aircraft'),
        ),
    ]
