# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:42
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_auto_20171017_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftgalleryimage',
            options={'ordering': ['image_order']},
        ),
        migrations.AddField(
            model_name='aircraftgalleryimage',
            name='image_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='aircraftgalleryimage',
            name='aircraft',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.Aircraft'),
        ),
    ]
