# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_auto_20171017_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='designation',
            field=models.CharField(default='TEST', max_length=12, verbose_name='Aircraft Type Designation'),
            preserve_default=False,
        ),
    ]
