# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:43
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_aircraft_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftequipment',
            name='aircraft',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='aircraft.Aircraft'),
        ),
    ]
