# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:26
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0006_auto_20171024_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftequipment',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured on Frontpage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aircraftgalleryimage',
            name='aircraft',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='aircraft.Aircraft'),
        ),
    ]
