# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0007_auto_20171025_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftEquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['category_order'],
            },
        ),
        migrations.AddField(
            model_name='aircraftequipment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='aircraft.AircraftEquipmentCategory'),
            preserve_default=False,
        ),
    ]
