# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0008_auto_20171028_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftequipmentcategory',
            options={'ordering': ['category_order'], 'verbose_name_plural': 'Equipment Categories'},
        ),
    ]
