# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0009_auto_20171029_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='rate_dry',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dry Rate'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='rate_wet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wet Rate'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Speed in Knots'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='useful_load',
            field=models.IntegerField(blank=True, null=True, verbose_name='Useful Load'),
        ),
    ]
